server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: FOOD-SERVICE
  datasource:
    url: jdbc:mysql://mysql-db.c54vu5cxnk6k.us-east-1.rds.amazonaws.com:3306/delivery_food_db
    username: loschachos
    password: abcde12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect